Increase RHEL testing MC startup timeout [DI-435]
When testing RHEL images, [the tests often fail](https://github.com/hazelcast/hazelcast-docker/actions/workflows/tag_image_push_rhel.yml), most recently because the MC pod failed to start in time:
> error: timed out waiting for the condition on pods/test-13631969388-1-17-hazelcast-enterprise-mancenter-0

```
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
{...}
  Warning  Unhealthy               2m13s (x6 over 4m13s)   kubelet                  Liveness probe failed: Get "http://10.131.0.66:8081/health": dial tcp 10.131.0.66:8081: connect: connection refused
```

I've done [lots of investigation to try to get more information](https://hazelcast.atlassian.net/browse/DI-435) without any success, but what I _have_ noticed is that even on [successful tests](https://github.com/hazelcast/hazelcast-docker/actions/runs/13631962459), we still have multiple failures before MC is up-and-running:
```
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       True 
  ContainersReady             True 
  PodScheduled                True 
{...}
  Warning  Unhealthy               101s (x2 over 111s)  kubelet                  Liveness probe failed: Get "http://10.131.0.61:8081/health": dial tcp 10.131.0.61:8081: connect: connection refused
```

My _assumption_ is that the timeout is too low (in fact, the timeout doesn't make sense at all due to the flakey nature) and as such the build failures are abrirtary - which increasing the timeout _partially_ addresses.

Fixes: [DI-435](https://hazelcast.atlassian.net/browse/DI-435)

Post-merge actions:
- [ ] backport
- [ ] retag