Fix `tag_image_push_rhel.yml` for `push` triggers
In https://github.com/hazelcast/hazelcast-docker/pull/844, the `HZ_VERSION` is computed using the `required` `HZ_VERSION` `input`.

However, this is only `required` for `workflow_dispatch` triggers - it can _also_ be triggered by `push`, where it's instead empty - causing an [action failure](https://github.com/hazelcast/hazelcast-docker/actions/runs/12521044660):
```
Run madhead/semver-utils@latest
Error: Input required and not supplied: version
```

The workflow already derived an appropriate `HZ_VERSION` environment variable by validating the one in the in the `input` - updated to use this instead as it _should_ have done in the first place.